spring:
  datasource:
    url: jdbc:mysql://123.56.162.106:3306/spring_content_center
    hikari:
      username: root
      password: ${dbpassword}
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081