spring:
  datasource:
    url: jdbc:mysql://123.56.162.106:3306/spring_content_center
    hikari:
      username: root
      password: ${dbpassword}
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          instancevalue: nihao
          version: v1
  application:
    #注意，服务名称不要用下划线
    name: content-center
server:
  port: 8081

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.gdrg.contentcenter.feignClient.UserCenterFeignClient: debug
